#!/usr/bin/env python3
import sys

def lex_code(code):
    tokens = []
    s = ''
    for i in range(len(code)):
        if code[i] in '{}(); ':
            if s:
                tokens.append(s)
                s = ''
            if code[i] != ' ':
                tokens.append(code[i])
        else:
            if code[i] != '\n':
                s += code[i]
    return tokens

with open(sys.argv[1], 'r') as f:
    code = f.read()
    print(lex_code(code))
